spring.application.name=gateway
server.port=8080

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/


# 2. Habilitar Actuator para ver las rutas
management.endpoints.web.exposure.include=gateway,health
management.endpoint.gateway.enabled=true

# 3. Logs para ver el ruteo reactivo
logging.level.org.springframework.cloud.gateway=TRACE