spring.application.name=microservice-location

server.port=8082
#PRUEBA
#spring.profiles.active=dev

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

eureka.instance.prefer-ip-address=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Configuración de OpenFeign (Tiempos de espera)
spring.cloud.openfeign.client.config.default.connectTimeout=5000
 spring.cloud.openfeign.client.config.default.readTimeout=5000