spring.application.name=microservice-location

server.port=8082
#PRUEBA
#spring.profiles.active=dev

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Configuración de OpenFeign (Tiempos de espera)
# spring.cloud.openfeign.client.config.default.connectTimeout=5000
# spring.cloud.openfeign.client.config.default.readTimeout=5000