spring.application.name=microservice-character

server.port=8081

eureka.client.enabled=false
#PRUEBA
spring.profiles.active=dev

# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true
# eureka.instance.prefer-ip-address=true

# Configuración de OpenFeign (Tiempos de espera)
# spring.cloud.openfeign.client.config.default.connectTimeout=5000
# spring.cloud.openfeign.client.config.default.readTimeout=5000