spring.application.name=microservice-character
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/charactersdev
spring.datasource.username=postgres
spring.datasource.password=Pancito11ProMax...
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.enabled=false